python train.py \
    --model resnet \
    --folder_structure ImageFolder \
    --folder_name PokemonData \
    --epochs 50 \
    --batch_size 64 \
    --lr 1e-5 \
    --val_split 0.1 \
    --amp \
    --save_checkpoints \
    --checkpoint_dir ./Poke \
    --project pokemon-classification \
